Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net20,R105-2)
Netlist(Add,unnamed_net20,R106-1)
Netlist(Add,unnamed_net20,U101B-2)
Netlist(Add,unnamed_net19,R106-2)
Netlist(Add,unnamed_net19,U101B-5)
Netlist(Add,unnamed_net19,R102-1)
Netlist(Add,unnamed_net18,R102-2)
Netlist(Add,unnamed_net18,Q103-B)
Netlist(Add,unnamed_net18,Q104-B)
Netlist(Add,unnamed_net17,L102-2)
Netlist(Add,unnamed_net17,Q103-E)
Netlist(Add,unnamed_net17,Q104-E)
Netlist(Add,unnamed_net16,L101-2)
Netlist(Add,unnamed_net16,C101-2)
Netlist(Add,unnamed_net15,R103-1)
Netlist(Add,unnamed_net15,R104-1)
Netlist(Add,unnamed_net15,U101A-2)
Netlist(Add,unnamed_net14,R104-2)
Netlist(Add,unnamed_net14,R105-1)
Netlist(Add,unnamed_net14,U101A-5)
Netlist(Add,unnamed_net14,R101-1)
Netlist(Add,unnamed_net13,R101-2)
Netlist(Add,unnamed_net13,Q101-B)
Netlist(Add,unnamed_net13,Q102-B)
Netlist(Add,unnamed_net12,C101-1)
Netlist(Add,unnamed_net12,Q101-E)
Netlist(Add,unnamed_net12,Q102-E)
Netlist(Add,unnamed_net11,CONN?-2)
Netlist(Add,unnamed_net11,C103-2)
Netlist(Add,unnamed_net11,T2-4)
Netlist(Add,unnamed_net10,CONN?-1)
Netlist(Add,unnamed_net10,C103-1)
Netlist(Add,unnamed_net10,T2-2)
Netlist(Add,PRIB,L102-1)
Netlist(Add,PRIB,T1-2)
Netlist(Add,PRIA,L101-1)
Netlist(Add,PRIA,T1-1)
Netlist(Add,unnamed_net9,T2-1)
Netlist(Add,unnamed_net9,C102-1)
Netlist(Add,unnamed_net9,D102-2)
Netlist(Add,unnamed_net9,D103-2)
Netlist(Add,unnamed_net8,T1-4)
Netlist(Add,unnamed_net8,D104-2)
Netlist(Add,unnamed_net8,D103-1)
Netlist(Add,unnamed_net7,D102-1)
Netlist(Add,unnamed_net7,T1-3)
Netlist(Add,unnamed_net7,D101-2)
Netlist(Add,unnamed_net6,T2-3)
Netlist(Add,unnamed_net6,C102-2)
Netlist(Add,unnamed_net6,D104-1)
Netlist(Add,unnamed_net6,D101-1)
Netlist(Add,unnamed_net5,RP201-3)
Netlist(Add,unnamed_net5,C205-2)
Netlist(Add,unnamed_net5,U201A-1)
Netlist(Add,unnamed_net4,R204-1)
Netlist(Add,unnamed_net4,R205-1)
Netlist(Add,unnamed_net4,C201-2)
Netlist(Add,unnamed_net3,C202-2)
Netlist(Add,unnamed_net3,R204-2)
Netlist(Add,unnamed_net3,R203-1)
Netlist(Add,OSC,U101A-1)
Netlist(Add,OSC,R205-2)
Netlist(Add,OSC,C203-1)
Netlist(Add,OSC,R202-1)
Netlist(Add,GND,C105-2)
Netlist(Add,GND,C108-2)
Netlist(Add,GND,C109-2)
Netlist(Add,GND,C107-2)
Netlist(Add,GND,C104-2)
Netlist(Add,GND,C105-1)
Netlist(Add,GND,U101B-4)
Netlist(Add,GND,Q104-C)
Netlist(Add,GND,Q102-C)
Netlist(Add,GND,RP201-2)
Netlist(Add,GND,C206-1)
Netlist(Add,GND,C205-1)
Netlist(Add,GND,U201A-4)
Netlist(Add,GND,U201B-4)
Netlist(Add,P12VD,C109-1)
Netlist(Add,P12VD,C105-1)
Netlist(Add,P12VD,U101B-3)
Netlist(Add,P12VD,C108-1)
Netlist(Add,P12VD,C105-2)
Netlist(Add,P12VD,Q103-C)
Netlist(Add,P12VD,C107-1)
Netlist(Add,P12VD,C104-1)
Netlist(Add,P12VD,Q101-C)
Netlist(Add,P12VD,RP201-1)
Netlist(Add,P12VD,U201A-3)
Netlist(Add,P12VD,C206-2)
Netlist(Add,P12VD,U201B-3)
Netlist(Add,unnamed_net2,R203-2)
Netlist(Add,unnamed_net2,R201-2)
Netlist(Add,unnamed_net2,U201B-5)
Netlist(Add,unnamed_net1,R202-2)
Netlist(Add,unnamed_net1,R201-1)
Netlist(Add,unnamed_net1,U201B-2)
Netlist(Add,VREF,R103-2)
Netlist(Add,VREF,U101B-1)
Netlist(Add,VREF,U201A-5)
Netlist(Add,VREF,U201A-2)
Netlist(Add,VREF,C202-1)
Netlist(Add,VREF,C201-1)
Netlist(Add,VREF,C203-2)
Netlist(Add,VREF,U201B-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"L102","sandals","unknown")
ElementSetAttr("L102","device","common mode choke")
ElementSetAttr("L102","manufacturer","unknown")
ElementSetAttr("L102","manufacturer_part_number","unknown")
ElementSetAttr("L102","vendor","unknown")
ElementSetAttr("L102","vendor_part_number","unknown")
ChangePinName("L102", 1, "1")
ChangePinName("L102", 2, "2")
ElementList(Need,"L101","sandals","unknown")
ElementSetAttr("L101","device","common mode choke")
ElementSetAttr("L101","manufacturer","unknown")
ElementSetAttr("L101","manufacturer_part_number","unknown")
ElementSetAttr("L101","vendor","unknown")
ElementSetAttr("L101","vendor_part_number","unknown")
ChangePinName("L101", 1, "1")
ChangePinName("L101", 2, "2")
ElementList(Need,"C108","1206","10uF")
ElementSetAttr("C108","device","POLARIZED_CAPACITOR")
ElementSetAttr("C108","manufacturer","unknown")
ElementSetAttr("C108","manufacturer_part_number","unknown")
ElementSetAttr("C108","vendor","unknown")
ElementSetAttr("C108","vendor_part_number","unknown")
ChangePinName("C108", 2, "-")
ChangePinName("C108", 1, "+")
ElementList(Need,"C109","rcy(2.50mm, pol=bar+sign, dia=6.3 mm, pin_ringdia=1.75mm, pin_drill=0.70mm)","100uF")
ElementSetAttr("C109","device","POLARIZED_CAPACITOR")
ElementSetAttr("C109","manufacturer","unknown")
ElementSetAttr("C109","manufacturer_part_number","unknown")
ElementSetAttr("C109","vendor","unknown")
ElementSetAttr("C109","vendor_part_number","unknown")
ChangePinName("C109", 2, "-")
ChangePinName("C109", 1, "+")
ElementList(Need,"C107","1206","10uF")
ElementSetAttr("C107","device","POLARIZED_CAPACITOR")
ElementSetAttr("C107","manufacturer","unknown")
ElementSetAttr("C107","manufacturer_part_number","unknown")
ElementSetAttr("C107","vendor","unknown")
ElementSetAttr("C107","vendor_part_number","unknown")
ChangePinName("C107", 2, "-")
ChangePinName("C107", 1, "+")
ElementList(Need,"C104","1206","0.1uF")
ElementSetAttr("C104","device","CAPACITOR")
ElementSetAttr("C104","manufacturer","unknown")
ElementSetAttr("C104","manufacturer_part_number","unknown")
ElementSetAttr("C104","vendor","unknown")
ElementSetAttr("C104","vendor_part_number","unknown")
ChangePinName("C104", 2, "2")
ChangePinName("C104", 1, "1")
ElementList(Need,"C105","1206","0.1uF")
ElementSetAttr("C105","device","CAPACITOR")
ElementSetAttr("C105","manufacturer","unknown")
ElementSetAttr("C105","manufacturer_part_number","unknown")
ElementSetAttr("C105","vendor","unknown")
ElementSetAttr("C105","vendor_part_number","unknown")
ChangePinName("C105", 2, "2")
ChangePinName("C105", 1, "1")
ChangePinName("C105", 2, "2")
ChangePinName("C105", 1, "1")
ElementList(Need,"R103","0805","1K")
ElementSetAttr("R103","device","RESISTOR")
ElementSetAttr("R103","manufacturer","unknown")
ElementSetAttr("R103","manufacturer_part_number","unknown")
ElementSetAttr("R103","vendor","unknown")
ElementSetAttr("R103","vendor_part_number","unknown")
ChangePinName("R103", 1, "1")
ChangePinName("R103", 2, "2")
ElementList(Need,"R104","0805","13K")
ElementSetAttr("R104","device","RESISTOR")
ElementSetAttr("R104","manufacturer","unknown")
ElementSetAttr("R104","manufacturer_part_number","unknown")
ElementSetAttr("R104","vendor","unknown")
ElementSetAttr("R104","vendor_part_number","unknown")
ChangePinName("R104", 1, "1")
ChangePinName("R104", 2, "2")
ElementList(Need,"R105","0805","10K")
ElementSetAttr("R105","device","RESISTOR")
ElementSetAttr("R105","manufacturer","unknown")
ElementSetAttr("R105","manufacturer_part_number","unknown")
ElementSetAttr("R105","vendor","unknown")
ElementSetAttr("R105","vendor_part_number","unknown")
ChangePinName("R105", 1, "1")
ChangePinName("R105", 2, "2")
ElementList(Need,"R106","0805","10K")
ElementSetAttr("R106","device","RESISTOR")
ElementSetAttr("R106","manufacturer","unknown")
ElementSetAttr("R106","manufacturer_part_number","unknown")
ElementSetAttr("R106","vendor","unknown")
ElementSetAttr("R106","vendor_part_number","unknown")
ChangePinName("R106", 1, "1")
ChangePinName("R106", 2, "2")
ElementList(Need,"U101B","so(8)","unknown")
ElementSetAttr("U101B","device","OPAMP")
ElementSetAttr("U101B","manufacturer","unknown")
ElementSetAttr("U101B","manufacturer_part_number","unknown")
ElementSetAttr("U101B","vendor","unknown")
ElementSetAttr("U101B","vendor_part_number","unknown")
ChangePinName("U101B", 4, "V-")
ChangePinName("U101B", 3, "V+")
ChangePinName("U101B", 5, "out")
ChangePinName("U101B", 2, "in-")
ChangePinName("U101B", 1, "in+")
ElementList(Need,"R102","1206","100")
ElementSetAttr("R102","device","RESISTOR")
ElementSetAttr("R102","manufacturer","unknown")
ElementSetAttr("R102","manufacturer_part_number","unknown")
ElementSetAttr("R102","vendor","unknown")
ElementSetAttr("R102","vendor_part_number","unknown")
ChangePinName("R102", 1, "1")
ChangePinName("R102", 2, "2")
ElementList(Need,"Q103","TO-225AA","unknown")
ElementSetAttr("Q103","device","NPN_TRANSISTOR")
ElementSetAttr("Q103","manufacturer","unknown")
ElementSetAttr("Q103","manufacturer_part_number","unknown")
ElementSetAttr("Q103","vendor","unknown")
ElementSetAttr("Q103","vendor_part_number","unknown")
ChangePinName("Q103", B, "B")
ChangePinName("Q103", E, "E")
ChangePinName("Q103", C, "C")
ElementList(Need,"Q104","TO225AA","unknown")
ElementSetAttr("Q104","device","PNP_TRANSISTOR")
ElementSetAttr("Q104","manufacturer","unknown")
ElementSetAttr("Q104","manufacturer_part_number","unknown")
ElementSetAttr("Q104","vendor","unknown")
ElementSetAttr("Q104","vendor_part_number","unknown")
ChangePinName("Q104", B, "B")
ChangePinName("Q104", E, "E")
ChangePinName("Q104", C, "C")
ElementList(Need,"C101","acy(400)","1uF")
ElementSetAttr("C101","device","CAPACITOR")
ElementSetAttr("C101","manufacturer","unknown")
ElementSetAttr("C101","manufacturer_part_number","unknown")
ElementSetAttr("C101","vendor","unknown")
ElementSetAttr("C101","vendor_part_number","unknown")
ChangePinName("C101", 2, "2")
ChangePinName("C101", 1, "1")
ElementList(Need,"U101A","so(8)","unknown")
ElementSetAttr("U101A","device","OPAMP")
ElementSetAttr("U101A","manufacturer","unknown")
ElementSetAttr("U101A","manufacturer_part_number","unknown")
ElementSetAttr("U101A","vendor","unknown")
ElementSetAttr("U101A","vendor_part_number","unknown")
ChangePinName("U101A", 4, "V-")
ChangePinName("U101A", 3, "V+")
ChangePinName("U101A", 5, "out")
ChangePinName("U101A", 2, "in-")
ChangePinName("U101A", 1, "in+")
ElementList(Need,"R101","1206","100")
ElementSetAttr("R101","device","RESISTOR")
ElementSetAttr("R101","manufacturer","unknown")
ElementSetAttr("R101","manufacturer_part_number","unknown")
ElementSetAttr("R101","vendor","unknown")
ElementSetAttr("R101","vendor_part_number","unknown")
ChangePinName("R101", 1, "1")
ChangePinName("R101", 2, "2")
ElementList(Need,"Q101","TO-225AA","unknown")
ElementSetAttr("Q101","device","NPN_TRANSISTOR")
ElementSetAttr("Q101","manufacturer","unknown")
ElementSetAttr("Q101","manufacturer_part_number","unknown")
ElementSetAttr("Q101","vendor","unknown")
ElementSetAttr("Q101","vendor_part_number","unknown")
ChangePinName("Q101", B, "B")
ChangePinName("Q101", E, "E")
ChangePinName("Q101", C, "C")
ElementList(Need,"Q102","TO225AA","unknown")
ElementSetAttr("Q102","device","PNP_TRANSISTOR")
ElementSetAttr("Q102","manufacturer","unknown")
ElementSetAttr("Q102","manufacturer_part_number","unknown")
ElementSetAttr("Q102","vendor","unknown")
ElementSetAttr("Q102","vendor_part_number","unknown")
ChangePinName("Q102", B, "B")
ChangePinName("Q102", E, "E")
ChangePinName("Q102", C, "C")
ElementList(Need,"CONN?","unknown","unknown")
ElementSetAttr("CONN?","device","CONNECTOR_2")
ElementSetAttr("CONN?","manufacturer","unknown")
ElementSetAttr("CONN?","manufacturer_part_number","unknown")
ElementSetAttr("CONN?","vendor","unknown")
ElementSetAttr("CONN?","vendor_part_number","unknown")
ChangePinName("CONN?", 1, "1")
ChangePinName("CONN?", 2, "2")
ElementList(Need,"C103","unknown","4.7uF")
ElementSetAttr("C103","device","POLARIZED_CAPACITOR")
ElementSetAttr("C103","manufacturer","unknown")
ElementSetAttr("C103","manufacturer_part_number","unknown")
ElementSetAttr("C103","vendor","unknown")
ElementSetAttr("C103","vendor_part_number","unknown")
ChangePinName("C103", 2, "-")
ChangePinName("C103", 1, "+")
ElementList(Need,"T2","unknown","unknown")
ElementSetAttr("T2","device","TRANSFORMER")
ElementSetAttr("T2","manufacturer","unknown")
ElementSetAttr("T2","manufacturer_part_number","unknown")
ElementSetAttr("T2","vendor","unknown")
ElementSetAttr("T2","vendor_part_number","unknown")
ChangePinName("T2", 4, "4")
ChangePinName("T2", 3, "3")
ChangePinName("T2", 2, "2")
ChangePinName("T2", 1, "1")
ElementList(Need,"T1","unknown","unknown")
ElementSetAttr("T1","device","TRANSFORMER")
ElementSetAttr("T1","manufacturer","unknown")
ElementSetAttr("T1","manufacturer_part_number","unknown")
ElementSetAttr("T1","vendor","unknown")
ElementSetAttr("T1","vendor_part_number","unknown")
ChangePinName("T1", 4, "4")
ChangePinName("T1", 3, "3")
ChangePinName("T1", 2, "2")
ChangePinName("T1", 1, "1")
ElementList(Need,"C102","unknown","4.7uF")
ElementSetAttr("C102","device","POLARIZED_CAPACITOR")
ElementSetAttr("C102","manufacturer","unknown")
ElementSetAttr("C102","manufacturer_part_number","unknown")
ElementSetAttr("C102","vendor","unknown")
ElementSetAttr("C102","vendor_part_number","unknown")
ChangePinName("C102", 2, "-")
ChangePinName("C102", 1, "+")
ElementList(Need,"D104","sandals","unknown")
ElementSetAttr("D104","device","DIODE")
ElementSetAttr("D104","manufacturer","unknown")
ElementSetAttr("D104","manufacturer_part_number","unknown")
ElementSetAttr("D104","vendor","unknown")
ElementSetAttr("D104","vendor_part_number","unknown")
ChangePinName("D104", 2, "2")
ChangePinName("D104", 1, "1")
ElementList(Need,"D102","sandals","unknown")
ElementSetAttr("D102","device","DIODE")
ElementSetAttr("D102","manufacturer","unknown")
ElementSetAttr("D102","manufacturer_part_number","unknown")
ElementSetAttr("D102","vendor","unknown")
ElementSetAttr("D102","vendor_part_number","unknown")
ChangePinName("D102", 2, "2")
ChangePinName("D102", 1, "1")
ElementList(Need,"D103","sandals","unknown")
ElementSetAttr("D103","device","DIODE")
ElementSetAttr("D103","manufacturer","unknown")
ElementSetAttr("D103","manufacturer_part_number","unknown")
ElementSetAttr("D103","vendor","unknown")
ElementSetAttr("D103","vendor_part_number","unknown")
ChangePinName("D103", 2, "2")
ChangePinName("D103", 1, "1")
ElementList(Need,"D101","sandals","unknown")
ElementSetAttr("D101","device","DIODE")
ElementSetAttr("D101","manufacturer","unknown")
ElementSetAttr("D101","manufacturer_part_number","unknown")
ElementSetAttr("D101","vendor","unknown")
ElementSetAttr("D101","vendor_part_number","unknown")
ChangePinName("D101", 2, "2")
ChangePinName("D101", 1, "1")
ElementList(Need,"RP201","SOT-323","10K")
ElementSetAttr("RP201","device","unknown")
ElementSetAttr("RP201","manufacturer","unknown")
ElementSetAttr("RP201","manufacturer_part_number","unknown")
ElementSetAttr("RP201","vendor","unknown")
ElementSetAttr("RP201","vendor_part_number","unknown")
ChangePinName("RP201", 1, "R1")
ChangePinName("RP201", 3, "RCOM")
ChangePinName("RP201", 2, "R2")
ElementList(Need,"C206","1206","0.1uF")
ElementSetAttr("C206","device","CAPACITOR")
ElementSetAttr("C206","manufacturer","unknown")
ElementSetAttr("C206","manufacturer_part_number","unknown")
ElementSetAttr("C206","vendor","unknown")
ElementSetAttr("C206","vendor_part_number","unknown")
ChangePinName("C206", 2, "2")
ChangePinName("C206", 1, "1")
ChangePinName("C206", 2, "2")
ChangePinName("C206", 1, "1")
ElementList(Need,"C205","acy(197)","10nF")
ElementSetAttr("C205","device","CAPACITOR")
ElementSetAttr("C205","manufacturer","unknown")
ElementSetAttr("C205","manufacturer_part_number","unknown")
ElementSetAttr("C205","vendor","unknown")
ElementSetAttr("C205","vendor_part_number","unknown")
ChangePinName("C205", 2, "2")
ChangePinName("C205", 1, "1")
ElementList(Need,"U201A","so(8)","unknown")
ElementSetAttr("U201A","device","OPAMP")
ElementSetAttr("U201A","manufacturer","unknown")
ElementSetAttr("U201A","manufacturer_part_number","unknown")
ElementSetAttr("U201A","vendor","unknown")
ElementSetAttr("U201A","vendor_part_number","unknown")
ChangePinName("U201A", 4, "V-")
ChangePinName("U201A", 3, "V+")
ChangePinName("U201A", 5, "out")
ChangePinName("U201A", 2, "in-")
ChangePinName("U201A", 1, "in+")
ElementList(Need,"R205","0805","1K")
ElementSetAttr("R205","device","RESISTOR")
ElementSetAttr("R205","manufacturer","unknown")
ElementSetAttr("R205","manufacturer_part_number","unknown")
ElementSetAttr("R205","vendor","unknown")
ElementSetAttr("R205","vendor_part_number","unknown")
ChangePinName("R205", 1, "1")
ChangePinName("R205", 2, "2")
ElementList(Need,"R204","0805","1K")
ElementSetAttr("R204","device","RESISTOR")
ElementSetAttr("R204","manufacturer","unknown")
ElementSetAttr("R204","manufacturer_part_number","unknown")
ElementSetAttr("R204","vendor","unknown")
ElementSetAttr("R204","vendor_part_number","unknown")
ChangePinName("R204", 1, "1")
ChangePinName("R204", 2, "2")
ElementList(Need,"C201","KEMET_MMK5xxxK63J0xL4.subc.lht","3.3nF")
ElementSetAttr("C201","device","CAPACITOR")
ElementSetAttr("C201","manufacturer","unknown")
ElementSetAttr("C201","manufacturer_part_number","unknown")
ElementSetAttr("C201","vendor","unknown")
ElementSetAttr("C201","vendor_part_number","unknown")
ChangePinName("C201", 2, "2")
ChangePinName("C201", 1, "1")
ElementList(Need,"C202","KEMET_MMK5xxxK63J0xL4.subc.lht","3.3nF")
ElementSetAttr("C202","device","CAPACITOR")
ElementSetAttr("C202","manufacturer","unknown")
ElementSetAttr("C202","manufacturer_part_number","unknown")
ElementSetAttr("C202","vendor","unknown")
ElementSetAttr("C202","vendor_part_number","unknown")
ChangePinName("C202", 2, "2")
ChangePinName("C202", 1, "1")
ElementList(Need,"R203","0805","1K")
ElementSetAttr("R203","device","RESISTOR")
ElementSetAttr("R203","manufacturer","unknown")
ElementSetAttr("R203","manufacturer_part_number","unknown")
ElementSetAttr("R203","vendor","unknown")
ElementSetAttr("R203","vendor_part_number","unknown")
ChangePinName("R203", 1, "1")
ChangePinName("R203", 2, "2")
ElementList(Need,"C203","KEMET_MMK5xxxK63J0xL4.subc.lht","3.3nF")
ElementSetAttr("C203","device","CAPACITOR")
ElementSetAttr("C203","manufacturer","unknown")
ElementSetAttr("C203","manufacturer_part_number","unknown")
ElementSetAttr("C203","vendor","unknown")
ElementSetAttr("C203","vendor_part_number","unknown")
ChangePinName("C203", 2, "2")
ChangePinName("C203", 1, "1")
ElementList(Need,"R202","0805","5K")
ElementSetAttr("R202","device","RESISTOR")
ElementSetAttr("R202","manufacturer","unknown")
ElementSetAttr("R202","manufacturer_part_number","unknown")
ElementSetAttr("R202","vendor","unknown")
ElementSetAttr("R202","vendor_part_number","unknown")
ChangePinName("R202", 1, "1")
ChangePinName("R202", 2, "2")
ElementList(Need,"R201","0805","180K")
ElementSetAttr("R201","device","RESISTOR")
ElementSetAttr("R201","manufacturer","unknown")
ElementSetAttr("R201","manufacturer_part_number","unknown")
ElementSetAttr("R201","vendor","unknown")
ElementSetAttr("R201","vendor_part_number","unknown")
ChangePinName("R201", 1, "1")
ChangePinName("R201", 2, "2")
ElementList(Need,"U201B","so(8)","unknown")
ElementSetAttr("U201B","device","OPAMP")
ElementSetAttr("U201B","manufacturer","unknown")
ElementSetAttr("U201B","manufacturer_part_number","unknown")
ElementSetAttr("U201B","vendor","unknown")
ElementSetAttr("U201B","vendor_part_number","unknown")
ChangePinName("U201B", 4, "V-")
ChangePinName("U201B", 3, "V+")
ChangePinName("U201B", 5, "out")
ChangePinName("U201B", 2, "in-")
ChangePinName("U201B", 1, "in+")
ElementList(Done)
